"""empty message

Revision ID: 2f71e79a20f3
Revises: ad45baa17764
Create Date: 2020-07-06 15:36:48.286031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f71e79a20f3'
down_revision = 'ad45baa17764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('countries_dive_avg_depth', sa.String(), nullable=False),
    sa.Column('latitude', sa.String(), nullable=False),
    sa.Column('longitude', sa.String(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('country_countries_dive_name_key', 'country', type_='unique')
    op.drop_column('country', 'countries_dive_avg_depth')
    op.drop_column('country', 'latitude')
    op.drop_column('country', 'longitude')
    op.drop_column('country', 'countries_dive_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('countries_dive_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('country', sa.Column('longitude', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('country', sa.Column('latitude', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('country', sa.Column('countries_dive_avg_depth', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('country_countries_dive_name_key', 'country', ['countries_dive_name'])
    op.drop_table('sites')
    # ### end Alembic commands ###
