"""empty message

Revision ID: 63e7de9532fe
Revises: 7596b0c60250
Create Date: 2020-07-14 21:42:46.851136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63e7de9532fe'
down_revision = '7596b0c60250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('country')
    op.add_column('sites', sa.Column('countries_name', sa.String(), nullable=False))
    op.alter_column('sites', 'site_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('sites_country_id_fkey', 'sites', type_='foreignkey')
    op.drop_column('sites', 'country_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('country_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('sites_country_id_fkey', 'sites', 'country', ['country_id'], ['id'], onupdate='CASCADE')
    op.alter_column('sites', 'site_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('sites', 'countries_name')
    op.create_table('country',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('countries_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='country_pkey'),
    sa.UniqueConstraint('id', name='country_id_key')
    )
    # ### end Alembic commands ###
