"""empty message

Revision ID: 7596b0c60250
Revises: 2f71e79a20f3
Create Date: 2020-07-06 15:49:07.580083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7596b0c60250'
down_revision = '2f71e79a20f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('site_name', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'sites', ['site_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sites', type_='unique')
    op.drop_column('sites', 'site_name')
    # ### end Alembic commands ###
