"""empty message

Revision ID: 04082da481e0
Revises: 434d1a3e9b16
Create Date: 2020-09-19 13:04:01.861672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04082da481e0'
down_revision = '434d1a3e9b16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('image_file', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image_file')
    op.drop_table('post')
    # ### end Alembic commands ###
