"""empty message

Revision ID: 434d1a3e9b16
Revises: 
Create Date: 2020-07-14 21:53:22.167047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '434d1a3e9b16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(), nullable=True),
    sa.Column('countries_name', sa.String(), nullable=False),
    sa.Column('countries_dive_avg_depth', sa.String(), nullable=False),
    sa.Column('latitude', sa.String(), nullable=False),
    sa.Column('longitude', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sites')
    # ### end Alembic commands ###
